-- ▄    ▄▄▄  ▄▄ ▄▄  ▄▄▄▄ ▄▄▄▄▄▄ ▄▄    
--  ▀▄ ██▀██ ▀█▄█▀ ██▀▀▀   ██   ██    
-- ▄▀  ██▀██ ██ ██ ▀████   ██   ██▄▄▄ 

hl.on("hyprland.start", function()
    hl.exec_cmd("ambxst")
end)


-- ▄    ▄▄▄  ▄▄ ▄▄  ▄▄▄▄ ▄▄▄▄▄▄ ▄▄    
--  ▀▄ ██▀██ ▀█▄█▀ ██▀▀▀   ██   ██    
-- ▄▀  ██▀██ ██ ██ ▀████   ██   ██▄▄▄ 

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = "rgb(edc3c1)",
            inactive_border = "rgb(2c2a38)",
        },
        layout = "dwindle",
    },
    decoration = {
        rounding = 16,
        active_opacity = 1.00,
        inactive_opacity = 1.00,
        shadow = {
            enabled = true,
            range = 8,
            color = "rgba(00000080)",
        },
        blur = {
            enabled = true,
            size = 4,
            passes = 2,
        },
    },
})

hl.config({
    animations = { enabled = true },
})

hl.curve("myBezier", { type = "bezier", points = { {0.4, 0.0}, {0.2, 1.0} } })

hl.animation({ leaf = "windows", enabled = true, speed = 2.5, bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 2.5, bezier = "myBezier" })
hl.animation({ leaf = "fade", enabled = true, speed = 2.5, bezier = "myBezier" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.5, bezier = "myBezier", style = "slidefade 20%" })

-- Generated by axctl LuaGenerator (Keybinds)
-- Do not edit manually!

hl.bind("SUPER + Super_L", hl.dsp.exec_cmd("ambxst run launcher"))
hl.bind("SUPER + A", hl.dsp.exec_cmd("ambxst run assistant"))
hl.bind("SUPER + PERIOD", hl.dsp.exec_cmd("ambxst run emoji"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("ambxst run notes"))
hl.bind("SUPER + COMMA", hl.dsp.exec_cmd("ambxst run wallpapers"))
hl.bind("SUPER + TAB", hl.dsp.exec_cmd("ambxst run overview"))
hl.bind("SUPER + ESCAPE", hl.dsp.exec_cmd("ambxst run powermenu"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("ambxst run config"))
hl.bind("SUPER + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("SUPER + S", hl.dsp.exec_cmd("ambxst run tools"))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("ambxst run screenshot"))
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("ambxst run screenrecord"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("ambxst run lens"))
hl.bind("SUPER + ALT + B", hl.dsp.exec_cmd("ambxst reload"))
hl.bind("SUPER + CTRL + ALT + B", hl.dsp.exec_cmd("ambxst quit"))
hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"))
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + R", hl.dsp.exec_cmd("hyprlauncher"))
hl.bind("SUPER + P", hl.dsp.window.pseudo())
hl.bind("SUPER + J", hl.dsp.exec_cmd("togglesplit"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("brave"))
hl.bind("SUPER + G", hl.dsp.exec_cmd("/home/cristiansrc/.local/bin/toggle_gemini.sh"))
hl.bind("SUPER + ALT + Z", hl.dsp.exec_cmd("zen-browser"))
hl.bind("SUPER + H", hl.dsp.exec_cmd("kitty -e glow -p /home/cristiansrc/Documentos/atajos.md"))
hl.bind("SUPER + ALT + V", hl.dsp.exec_cmd("code"))
hl.bind("SUPER + F", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("dbeaver"))
hl.bind("SUPER + ALT + G", hl.dsp.exec_cmd("brave --app=https://mail.google.com/"))
hl.bind("SUPER + SHIFT + G", hl.dsp.exec_cmd("goland"))
hl.bind("SUPER + ALT + P", hl.dsp.exec_cmd("/usr/pgadmin4/bin/pgadmin4"))
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("pycharm"))
hl.bind("SUPER + ALT + S", hl.dsp.exec_cmd("steam"))
hl.bind("SUPER + W", hl.dsp.exec_cmd("warp-terminal"))
hl.bind("SUPER + K", hl.dsp.exec_cmd("gitkraken"))
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind("PRINT", hl.dsp.exec_cmd("grimblast --notify copysave area"))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("grimblast --notify edit area"))
hl.bind("SUPER + ALT + M", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))
hl.bind("SUPER + ALT + A", hl.dsp.exec_cmd("/home/cristiansrc/.config/hypr/toggle_audio.sh"))
hl.bind("SUPER + ALT + J", hl.dsp.exec_cmd("/home/cristiansrc/Documentos/Proyectos/HyprMind/src/client.sh START"))
hl.bind("SUPER + ALT + J", hl.dsp.exec_cmd("/home/cristiansrc/Documentos/Proyectos/HyprMind/src/client.sh STOP"))

-- Generated by axctl LuaGenerator (Window Rules)
-- Do not edit manually!


-- Generated by axctl LuaGenerator (Layer Rules)
-- Do not edit manually!

hl.layer_rule({
    no_anim = true,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    blur = true,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    blur_popups = true,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    ignore_alpha = 1.00,
    match = { namespace = "quickshell" },
})

hl.layer_rule({
    no_anim = true,
    match = { namespace = "selection" },
})

hl.layer_rule({
    blur = true,
    ignore_alpha = 0.40,
    match = { namespace = "fabric" },
})

hl.layer_rule({
    no_anim = true,
    blur = true,
    blur_popups = true,
    ignore_alpha = 0.50,
    match = { namespace = "ambxst" },
})

hl.layer_rule({
    no_anim = true,
    blur = true,
    blur_popups = true,
    match = { namespace = "overview" },
})

hl.layer_rule({
    no_anim = true,
    blur = true,
    blur_popups = true,
    match = { namespace = "presets" },
})

